---
title: "R Notebook"
output: html_notebook
---

```{r}
getwd()
#setwd("/Users/jeya/Documents/GitHub/DHR-MP-ELISA") ## setwd for MAC
#setwd("G:/GITHUB/DHR-MP-ELISA") ## setwd for Windows Desktop
dir()

```

```{r}
library(tidyverse)
library(caret)
library(mgcv)
library(ggplot2)
library(splines)
```


```{r}
data1 <- read.csv("./CD_ACF_all.csv")
data1
unique(data$Category.x)

data <- data1 %>%
        mutate(Category.x = fct_relevel(Category.x, "NDM", "DM", "NMI", "NMO", "NS", "PDR"))
data$FN_ng.ml.sMP
```

```{r}
ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() + 
  geom_smooth()
```


```{r}
# Linear regression model y = b0 + b1x 

lm(FN_ng.ml.sMP ~ LDL_mg.dl, data = subset(data))
lm(FN_ng.ml.sMP ~ LDL_mg.dl, data = subset(data, Category.x =="NDM"))

cat<- unique(data$Category.x)
length(blood.param)
blood.param <- c(6, 11:13, 16:26)
blood.param[2]
colnames(data[3])
## Linear regression model for data
sink("FNm.txt", append = TRUE) #To write the for loop output to a file named "FNm.txt"
for(i in 1:length(blood.param)){
  for(j in 1:length(cat)){
    model <- paste("model", i,j, sep="")
    print(model)
    z <- blood.param[i]
    print(colnames(data[z]))
    print(cat[j])
    x <- (paste("FN_ng.ml.sMP ~ ", colnames(data[z])))
    m<- lm(as.formula(paste("FN_ng.ml.sMP ~ ", colnames(data[z]))), data=subset(data, Category.x == cat[j]))
    print(summary(assign(model, m)))
    }
} 
sink() # stop writing the output to the file


ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() + 
  geom_smooth(method = lm, formula = y ~ x) ## when variables are mapped to aes(), refer to the variables rather than giving the actual variable name

ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() + 
  stat_smooth(method = lm, formula = y ~ x) +
  facet_wrap(~Category.x) 
```

```{r}
## LOG TRANSFORMATION METHOD when you have non-linear relationship between variables, we can try log transformation

fn.lm.log <- lm(log(FN_ng.ml.sMP+1)~LDL_mg.dl, data) #the data has a zero value and hence, log(x+1) was used as log(0) if infinity and throws an error
summary(fn.lm.log)

ggplot(data, aes(x = LDL_mg.dl, y = log(FN_ng.ml.sMP+1))) +
  geom_point() +
  stat_smooth(method = lm, formula = y~x) +
  scale_y_log10()

ggplot(data, aes(x = LDL_mg.dl, log(FN_ng.ml.sMP+1))) +
  geom_point() +
  stat_smooth(method = lm, formula = y~x) +
  scale_y_log10() + 
  facet_wrap(~Category.x)
```

```{r}
## POLYNOMIAL REGRESSION
## The polynomial regression adds polynomial or quadratic terms to the regression equation: y = b0 + b1∗x +b2∗x^2

fn.lm.poly <- lm(FN_ng.ml.sMP ~ poly(LDL_mg.dl, 1, raw = TRUE), data) 
summary(fn.lm.poly)


## from the output it is evident that only polynomial term of 1 is only significant and above 2 is not.  Polynomial term = 1 is the same as linear model

ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() +
  stat_smooth(method = lm, formula = y~poly(x, 1))

ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() +
  stat_smooth(method = lm, formula = y~poly(x, 1)) +
  facet_wrap(~Category.x)
```


```{r}
knots <- quantile(data$FN_ng.ml.sMP, p = c(0.25, 0.50, 0.75), na.rm = TRUE)
fn.lm.spline <- lm(FN_ng.ml.sMP~bs(LDL_mg.dl, knots = knots), data)
summary(fn.lm.spline)

ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() +
  geom_smooth(method = lm, formula = y~splines::bs(x))

ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() +
  geom_smooth(method = lm, formula = y~splines::bs(x, df = 3)) +
  facet_wrap(~Category.x)

ggplot(data, aes(x = LDL_mg.dl, y = FN_ng.ml.sMP)) +
  geom_point() +
  geom_smooth(method = lm, formula = y~splines::bs(x)) +
  facet_wrap(~Category.x)
```

