---
title: "R Notebook"
output: html_notebook
---
```{r}
setwd("G:/GITHUB/DHR-MP-ELISA")
cd_data <- read.csv("./CD_ACF_all.csv", stringsAsFactors = FALSE)
cd_data
vwf <- read.csv("./vWF.csv", stringsAsFactors = FALSE)
colnames(vwf) <- c("S.ID", "serum.vwf")
vwf

```

```{r}
library("tidyverse")
library("ggplot2")
```

```{r}
vWF.data <- cd_data %>%
            full_join(vwf, by = "S.ID") 
vWF.data
write.csv(vWF.data, "MP_CAFv.csv")

vwf.com <- cd_data %>%
            inner_join(vwf, by = "S.ID") %>%
            mutate(Category.x = as.factor(Category.x))
vwf.com
```

```{r}

vwf.com <- vwf.com %>% 
            mutate(diabTreatment = str_replace(diabTreatment, "Oral Medicines\\+Insulin\\(3Yrs\\)|Oral Medicine \\+Insulin|Oral Medicines\\+Insulin ", "Oral Medicines\\+Insulin")) %>%
            mutate(diabTreatment = str_replace_all(diabTreatment, c("Oral Medicines "="Oral Medicines", "Nil"="No"))) 
            
```

```{r}
vwf.com
vwf.com %>%
  mutate(diabTreatment = as.factor(diabTreatment)) %>%
  filter(Category.x == "DM" | Category.x == "NMI" | Category.x == "PDR") %>%
  ggplot(aes(y = `A2M_ng.ml.sMP`, x = `serum.vwf`, color = Category.x, shape = diabTreatment, label = diabDuration )) +
  geom_point(size =2.5) 

vwf.com %>%
  mutate(diabTreatment = as.factor(diabTreatment)) %>%
  ggplot(aes(y = `CD41_ng.ml.sMP`, x = `serum.vwf`, color = Category.x, shape = diabTreatment, label = diabDuration )) +
  geom_point(size = 2) +
  geom_text(aes(label=ifelse(diabDuration>=10, as.integer(diabDuration), ""), nudge_x=-0.3)) 


vwf.com %>%
  lm(formula = serum.vwf~CD41_ng.ml.sMP) %>%
  summary()


vwf.com %>%
  ggplot(aes(y = `A2M_ng.ml.sMP`,x = `serum.vwf`, color = Category.x)) +
  geom_point(size = 3) + 
  facet_wrap(~Category.x) +
  geom_smooth(method = lm, formula=y~x, se = FALSE) +
  scale_y_log10()

summary(lm(serum.vwf~CD41_ng.ml.sMP, data = vwf.com))

vwf.com

boxplot(vwf.com$serum.vwf~vwf.com$Category.x)
boxplot(vwf.com$CD41_ng.ml.sMP~vwf.com$Category.x)

```
```{r}
colnames(vwf.com)
```

```{r}
unique(CD_ACF_com$diabTreatment)
CD_ACF_com <- CD_ACF_com %>% 
            mutate(diabTreatment = str_replace(diabTreatment, "Oral Medicines\\+Insulin\\(3Yrs\\)|Oral Medicine \\+Insulin|Oral Medicines\\+Insulin ", "Oral Medicines\\+Insulin")) %>%
            mutate(diabTreatment = str_replace_all(diabTreatment, c("Oral Medicines "="Oral Medicines", "Nil"="No", "Diet Control Only|Siddha Treatment" = "No"))) 
            
vwf.com
vwf.com %>%
  mutate(diabTreatment = as.factor(diabTreatment)) %>%
  filter(Category.x == "NDM" | Category.x == "NMI" | Category.x == "PDR") %>%
  ggplot(aes(y = `CD41_ng.ml.sMP`, x = `serum.vwf`, shape = Category.x, color = diabTreatment)) +
  geom_point(size =2) + 
  geom_text(aes(label = ifelse(HbA1c>10, as.integer(HbA1c), "")), nudge_y=-0.3, nudge_x=-0.3, size = 2)


vwf.com %>%
  mutate(diabTreatment = as.factor(diabTreatment)) %>%
  filter(Category.x == "NDM" | Category.x == "NMI" | Category.x == "PDR") %>%
  ggplot(aes(y = `CD41_ng.ml.sMP`, x = `serum.vwf`, shape = Category.x, color = diabTreatment)) +
  geom_point(size =2.5) + 
  geom_text(aes(label = ifelse(HbA1c>10, as.integer(HbA1c), "")), nudge_y=-0.3, nudge_x=-0.3, size =2.5) 

vwf.com %>%
  mutate(diabTreatment = as.factor(diabTreatment)) %>%
  filter(Category.x == "NDM" | Category.x == "NMI" | Category.x == "PDR") %>%
  ggplot(aes(y = `CD41_ng.ml.sMP`, x = `serum.vwf`, shape = Category.x, color = diabTreatment)) +
  geom_point(size =2.5) + 
  geom_text(aes(label = ifelse(ESR>22, as.integer(ESR), "")), nudge_y=-0.3, nudge_x=-0.3, size =2.5) 

vwf.com %>%
  mutate(diabTreatment = as.factor(diabTreatment)) %>%
  filter(Category.x == "NDM" | Category.x == "NMI" | Category.x == "PDR") %>%
  ggplot(aes(y = `CD41_ng.ml.sMP`, x = `serum.vwf`, shape = Category.x, color = diabTreatment)) +
  geom_point(size =2.5) + 
  geom_text(aes(label = ifelse(CRP_mg.l>=10, as.integer(CRP_mg.l), "")), nudge_y=-0.3, nudge_x=-0.3, size =2.5) 

colnames(vwf.com)

vwf.com %>%
  mutate(diabTreatment = as.factor(diabTreatment)) %>%
  filter(Category.x == "NDM" | Category.x == "NMI" | Category.x == "PDR") %>%
  ggplot(aes(y = `CD41_ng.ml.sMP`, x = `serum.vwf`, shape = Category.x, color = diabTreatment)) +
  geom_point(size =2.5) + 
  geom_text(aes(label = ifelse(CRP_mg.l>=10, as.integer(CRP_mg.l), "")), nudge_y=-0.3, nudge_x=-0.3, size =2.5) 

range(vwf.com$serum.vwf)
```
```{r}
colnames(vwf.com)
str(vwf.com)
df <- vwf.com
row.names(df) <- paste(df$Category.x, row.names(df), sep = "_")
colnames(df)
df1 <- df[,c(4,6,11:14,16:30)] 
df1
df1 <- drop_na(df1)
df1
mp_pca <- prcomp(df1)
mp_pca$x
#plot directly
plot(mp_pca$x[,1], mp_pca$x[,2])

#Revise plot using ggplot
df_out <- as.data.frame(mp_pca$x)
df_out$group <- sapply(str_split(as.character(row.names(df1)), "_"), "[[", 1)
df_out

#Essential library packages
library(ggplot2)
library(grid)
library(gridExtra)


ggplot(df_out, aes(x = PC1, y = PC2, color = group)) +
  geom_point()

## Plot with a theme
theme <- theme(panel.background = element_blank(), panel.border = element_rect(fill = NA), panel.grid.major = element_blank(), strip.background = element_blank(), axis.text.x = element_text(colour = "black"), axis.ticks = element_line(colour = "black"), plot.margin = unit(c(1,1,1,1), "line"))

## For the plot
ggplot(df_out, aes(x = PC1, y = PC2, color = group)) +
  geom_point() +
  theme

## Captions
ggplot(df_out, aes(x = PC1, y = PC2, color = group, label = row.names(df1))) +
  geom_point() +
  geom_text(size=2) +
  theme

## Change the order for sample groups
df_out$group <- factor(df_out$group, levels = c("NDM", "DM", "NMI", "NMO", "NS", "PDR"))

ggplot(df_out, aes(x = PC1, y = PC2, color = group, label = row.names(df1))) +
  geom_point() +
  theme 

## Save as PDF

plot <- ggplot(df_out, aes(x = PC1, y = PC2, color = group)) +
  geom_point() +
  theme

pdf("mp_pca.pdf", width = 10, height = 10)
library(gridExtra)
yy <- grid.arrange(plot, nrow = 1)
op <- par(no.readonly = TRUE)
par(op)
dev.off()

## Plot features that contribute to classification
df_out_r <- as.data.frame(mp_pca$rotation)
df_out_r$feature <- row.names(df_out_r)
df_out_r

ggplot(df_out_r, aes(x = PC1, y = PC2, label=feature, color = feature)) +
  geom_point() +
  theme +
  geom_text(size = 2)
  
```
```{r}

library(ggfortify)
df2 <- vwf.com
df2 <- drop_na(df2)
df2$Category.x <- factor(df2$Category.x, levels = c("NDM", "DM", "NMI", "NMO", "NS", "PDR"))
row.names(df2) <- paste(df2$Category.x, row.names(df2), sep = "_")
colnames(df2)
df3 <- df2[,c(4,6,11:14,16:30)] 
df3 <- drop_na(df3)


mp_pca <- prcomp(df3, scale. = TRUE)
#Color data points based on sample group
autoplot(mp_pca, data = df2, colour = "Category.x", frame = TRUE, frame.type = "norm")

## include data labels
autoplot(mp_pca, data = df2, colour = "Category.x", label = TRUE, label.size = 2) 


## Make plot without points ["label" is turned on with this option]
autoplot(mp_pca, data = df2, colour = "Category.x", shape = FALSE, label.size = 2)

## Draw eigenvectors by using "loadings = TRUE"
autoplot(mp_pca, data = df2, colour = "Category.x", loadings = TRUE)

## Add eigenvector labels
autoplot(mp_pca, data = df2, colour = "Category.x", 
         loadings = TRUE, loadings.colour = "maroon",
         loadings.label = TRUE, loadings.label.size = 3)

## Disable the scaling in autoplot
autoplot(mp_pca,  scale = 0, data = df2, colour = "Category.x")

## Plotting factor analysis
mp.factanal <- factanal(df3, factors = 3, scores = "regression")
autoplot(mp.factanal, data = df2, colour = "Category.x")
autoplot(mp.factanal, data = df2, colour = "Category.x", loadings = TRUE, loadings.label = TRUE, loadings.label.size = 3)

##Plotting k-means
set.seed(1)
autoplot(kmeans(df3, 6), data = df3, label = TRUE, label.size = 3)

## Local Fisher Discriminant Analysis (LFDA)
library(lfda)
model <- lfda(df3[,],df3[,5], r = 3, metric = "plain")

```

